### ISSUE TITLE
export to csv file

### ISSUE THREAD

**Issue by jharcum** [USGS-R/smwrBase#11]
I'm successfully using as.qw to create variables. However, in some cases i want to log transform the data, and export the results to a csv file. Exporting less-thans (i.e.,"<"), left censored (e.g., -Inf - 4) seem to work well. Interval censored also work well with positive values. However, if the interval censored has a negative initial value, importing the data into excel treats it as an equation. but if the field has a preceeding space, then the import seems ok.

In the attached example, note the difference between the 3rd and 4th row of data for the variable 'lnpp'. So, can you add a preceeding space so these imports work ok also? Thanks.

[ct1_1orig_2016_07_27_174516.zip](https://github.com/USGS-R/smwrBase/files/387309/ct1_1orig_2016_07_27_174516.zip)

**Comment by dlorenz-usgs** [comment]
The data in that column, or any column with censoring, cannot be
interpreted as numeric data. To import it into Excel, use the import data
option, set the delimiter to coma, and format the column as character.

**Comment by jharcum** [comment]
k.
