### ISSUE TITLE
regularSeries cut

### ISSUE THREAD

**Issue by jharcum** [USGS-R/smwrBase#8]
I'm using regularSeries and seeking to take a data set to a single value per month. But I'm getting different results.

Option 1: I use a pretty simple call with no begin/end values. However the end of 2014 is not filled in, which is what I want .... so to Option 2
----------------------------
> df1<- regularSeries(df[ ,names(df)=="secchi"] , df$date, which = mean,
+                     k.period = 1 )
> 
> df1ts <- ts(df1[ ,names(df1)=="Value"],start=1999,frequency=12)
> df1ts
      Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
1999 1.80 0.60 0.40 0.90 1.00 1.20 1.10 1.10 0.80 0.50 0.40 1.20
2000 0.80 0.80 0.60 0.50 0.85 0.70 1.05 1.05 1.20 1.40 1.00 0.60
2001 0.50 0.70 0.50 0.40 0.60 0.60 0.90 1.00 1.20 0.70 1.00 1.20
2002 1.00 0.70 0.70 0.55 0.55 0.60 0.95 1.05 1.10 1.10 1.00 0.60
2003 0.50   NA 0.60 0.35 0.55 0.30 0.45 0.45 0.50 0.40 0.20 0.20
2004 0.50 0.90 0.40 0.35 0.55 0.60 0.75 0.80 0.10 0.50 0.60 0.40
2005 0.30 0.60 0.70 0.30 0.60 0.65 0.45 0.45 0.70 0.70 0.40 0.30
2006 0.50 0.30 0.60 0.45 0.80 0.55 0.20 0.55 0.60 0.80 0.40 0.20
2007 0.40   NA 0.40 0.55 0.80 0.65 0.70 0.65 1.10 1.10 0.80 0.80
2008 0.30 0.20 0.20 0.60 0.70 0.50 0.80 0.65 0.80 0.90 0.90 0.30
2009   NA 0.50 0.30 0.40 0.60 0.70 0.90 0.65 0.80 0.60 0.60 0.60
2010   NA   NA 0.20 0.30 0.60 0.65 0.70 0.65 0.60 0.50 0.60 0.40
2011   NA 0.40 0.10 0.30 0.30 0.50 0.50 0.45 0.30 0.25 0.50 0.40
2012 0.40 0.30 0.70 0.50 0.40 0.60 0.40 0.55 0.80 0.60 0.40 0.50
2013 0.60 0.10 0.30 0.40 0.40 0.45 0.40 0.40 1.00 0.70 0.80 0.60
2014   NA 0.70 0.30   NA 0.35 0.40 0.60     

Option 2: I include begin/end to fill out the time series through the end of Dec 2014. All seems good; however, the Jan-May2014 values in example 1 of "NA 0.70 0.30   NA 0.35 0.40" vs. "NA 0.70 0.30 0.30 0.40"). In example 2, a value for May 1, 2014 gets cut into April while it is averaged in with May data in Example 1.

> df1<- regularSeries(df[ ,names(df)=="secchi"] , as.Date(df$date), 
+                     period = "month", which = mean,
+                        begin="1999-01-01",
+                        end  ="2015-01-01", k.period = 1)
> 
> df1ts <- ts(df1[ ,names(df1)=="Value"],start=1999,frequency=12)
> df1ts
      Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
1999 1.80 0.60 0.40 0.90 1.00 1.20 1.10 1.10 0.80 0.50 0.40 1.20
2000 0.80 0.80 0.60 0.50 0.85 0.70 1.05 1.05 1.20 1.40 1.00 0.60
2001 0.50 0.70 0.50 0.40 0.60 0.60 0.90 1.00 1.20 0.70 1.00 1.20
2002 1.00 0.70 0.70 0.55 0.55 0.60 0.95 1.05 1.10 1.10 1.00 0.60
2003 0.50   NA 0.60 0.35 0.55 0.30 0.45 0.45 0.50 0.40 0.20 0.20
2004 0.50 0.90 0.40 0.35 0.55 0.60 0.75 0.80 0.10 0.50 0.60 0.40
2005 0.30 0.60 0.70 0.30 0.60 0.65 0.45 0.45 0.70 0.70 0.40 0.30
2006 0.50 0.30 0.60 0.45 0.80 0.55 0.20 0.55 0.60 0.80 0.40 0.20
2007 0.40   NA 0.40 0.55 0.80 0.65 0.70 0.65 1.10 1.10 0.80 0.80
2008 0.30 0.20 0.20 0.60 0.70 0.50 0.80 0.65 0.80 0.90 0.90 0.30
2009   NA 0.50 0.30 0.40 0.60 0.70 0.90 0.65 0.80 0.60 0.60 0.60
2010   NA   NA 0.20 0.30 0.60 0.65 0.70 0.65 0.60 0.50 0.60 0.40
2011   NA 0.40 0.10 0.30 0.30 0.50 0.50 0.45 0.30 0.25 0.50 0.40
2012 0.40 0.30 0.70 0.50 0.40 0.60 0.40 0.55 0.80 0.60 0.40 0.50
2013 0.60 0.10 0.30 0.40 0.40 0.45 0.40 0.40 1.00 0.70 0.80 0.60
2014   NA 0.70 0.30 0.30 0.40 0.40 0.60   NA   NA   NA   NA   NA

**Comment by dlorenz-usgs** [comment]
Please include the data so that I can reproduce the results. Please send to
lorenz@usgs.

**Comment by jharcum** [comment]
Dave, here you go. My r script and data file. I added a 3rd option that included adding 12 hours to the date field. It seems to get the results I was expecting. So my suspicion is that a hard date of 5/1/2014 ( no time) is getting cut differently between the various options. So perhaps how I’m setting the begin/end dates is being treated different than when I let regularSeries set those values.

Jon Harcum
Direct: 864-650-5815
jon.harcum@tetratech.com<mailto:jon.harcum@tetratech.com>

**Comment by dlorenz-usgs** [comment]
Jon,
  Thanks. I had meetings all day yesterday, so I could not get to your
issue. The issue is kind of related to that date, but it is the result of
different time zones being associated with the cut dates than the sample
dates when begin and end are specified.
  I fixed the code, but you can use the current version because you do not
need to specify the begin date. I like using the with helper function, so
my revised expression looks like

df1 <- with(df, regularSeries(secchi, date, which=mean, k.period=1,
   end="2015-01-01"))

  Hope this all makes sense.
Dave

**Comment by jharcum** [comment]
Dave,
    Much thanks and appreciate the great service. (Yup, seems to work well)
