### ISSUE TITLE
regularSeries, 

### ISSUE THREAD

**Issue by jharcum** [USGS-R/smwrBase#9]
regularSeries seems to fail when times has a mixture of EDT and EST data and the variable tzone is computed internally as a vector rather than a single value. (

> times <- as.POSIXlt(ct1$date)
> times
  [1] "1999-03-17 EST" "1999-04-27 EDT" "1999-05-11 EDT" "1999-05-25 EDT" "1999-06-08 EDT" "1999-07-07 EDT"
  [7] "1999-07-20 EDT" "1999-08-04 EDT" "1999-08-17 EDT" "1999-09-21 EDT" "1999-10-06 EDT" "2000-03-14 EST"
...[removed for brevity]...
 [43] "2002-07-30 EDT" "2002-08-13 EDT" "2002-08-27 EDT" "2002-09-17 EDT" "2002-10-15 EDT" "2003-03-11 EST"
...[removed for brevity]...
 [73] "2005-04-05 EDT" "2005-04-19 EDT" "2005-05-11 EDT" "2005-05-25 EDT" "2005-06-14 EDT" "2005-06-28 EDT"
 [79] "2005-07-12 EDT" "2005-07-26 EDT" "2005-08-09 EDT" "2005-08-24 EDT" "2005-09-13 EDT" "2006-03-08 EST"
 [85] "2006-04-06 EDT" "2006-04-18 EDT" "2006-05-09 EDT" "2006-05-23 EDT" "2006-06-06 EDT" "2006-06-20 EDT"
...[removed for brevity]...
[169] "2013-09-17 EDT" "2013-10-14 EDT" "2014-05-13 EDT" "2014-06-03 EDT" "2014-07-08 EDT"

> tzone <- attr(times, "tzone")
> tzone
[1] "America/New_York" "EST"              "EDT"  

In the above example if I throw in a 
tzone <- tzone[1]
the rest of the code works fine.

Jon

**Comment by dlorenz-usgs** [comment]
Fascinating!. It does help to isolate the problem if you can more specific
instructions on the actual call--it took me some time to figure out that it
failed when begin or end were specified.

The failure occurs because the constructor, as.POSIXlt, does not accept a
value for tz that is longer than 1, even though the "POSIXlt" class allows
for one of length 3. This would actually seem to be a problem in R rather
than the regularSeries function.

What process generates the POSIXlt data with the tzone vector of length 3?

**Comment by jharcum** [comment]
Attached is a zipped file of the data set


1)      Sample code that creates the error:

load('ct1_2015_12_07_155521.rda')
ct1.ts <- regularSeries(rObj$tn , rObj$date,
                        period = "month", which = mean,
                        begin='1999-01-01', end = '2015-01-01', k.period = 1)


2)      line by line from regularSeries

#set arguments
x <-rObj$tn
times <- rObj$date
period="month"
which = mean
begin='1999-01-01'
end = '2015-01-01'
k.period = 1

# lines from regularSeries
times <- as.POSIXlt(times)
tzone <- attr(times, "tzone")
tzone     # PRINT OUT TZONE
if(missing(begin)) {
  begin <- floor_date(min(times, na.rm=TRUE), unit=period)
} else
  begin <- as.POSIXlt(begin, tz=tzone)
if(missing(end)) {
  end <- floor_date(max(times, na.rm=TRUE), unit=period)
  end <- seq(end, by=period, length=k.period+1)[k.period+1]
} else
  end <- as.POSIXlt(end, tz=tzone)

**Comment by jharcum** [comment]
... so the tzone <-attr(times, "tzone") is the culprit

**Comment by ldecicco-USGS** [comment]
I don't think there's an attachment option via gitHub. Could you describe how the .rda data was generated? (or, send me the data via email as well).

So, without seeing that....take with a grain of salt....

Generally, a vector of POSIX's has a single attribute for timezone. "America/New_York" will *print* EST and EDT, but the single attribute is "America/New_York". If you only had EST, the attribute should be "America/Jamaica". This is why I want to understand how the data was created...It's possible to override the attribute tzone, but having more than one will cause problems. I'm not shocked that some of these problems will be silent. 


Thanks for the feedback!

**Comment by dlorenz-usgs** [comment]
I think the culprit is storing data in POSIXlt format. Our recommendation has always been POSIXct. All I can say is the POSIXlt is poorly behaved for storing data, but very useful for data conversion. Below is some code that demonstrates the quirky (I think) behavior:

> tl <- as.POSIXlt("2001-04-05 12:00", tz="America/Chicago")
> tl
[1] "2001-04-05 12:00:00 CDT"
> attr(tl, "tzone")
[1] "America/Chicago"
> attr(tl, "tzone") <- "America/Denver"
> tl
[1] "2001-04-05 12:00:00 CDT"
> tc <- as.POSIXct("2001-04-05 12:00", tz="America/Chicago")
> tc
[1] "2001-04-05 12:00:00 CDT"
> attr(tc, "tzone")
[1] "America/Chicago"
> attr(tc, "tzone") <- "America/Denver"
> tc
[1] "2001-04-05 11:00:00 MDT"
> as.POSIXct(tl)
[1] "2001-04-05 12:00:00 MDT"

**Comment by jharcum** [comment]
In the data file that I sent via regular email to Laura and you yesterday (ct1_2015_12_07_155521.rda), the dates are stored as POSIXct ... so I agree about storing as POSIXct. However, in lines 59-60 of regularSeries, they are converted to POSIXlt as per below

  times <- as.POSIXlt(times)
  tzone <- attr(times, "tzone")

The issue that I've encountered is that tzone is returned as below
[1] "America/New_York" "EST"              "EDT"  

So, if i set the begin argument of regularSeries to a character string
begin='1999-01-01'

Then line 64 of regularSeries, begin <- as.POSIXlt(begin, tz=tzone), gives me

Error in strptime(xx, f <- "%Y-%m-%d %H:%M:%OS", tz = tz) : 
  invalid 'tz' value

On the other hand, if I edit line 64 of regularSeries as below, it works

begin <- as.POSIXlt(begin, tz=tzone[1])

So, my thinking is that the variable, tzone, needs to be a single value when applied to a single value like begin.

**Comment by dlorenz-usgs** [comment]
That change can be made and I will make it to protect against users
providing POSIXlt data with a tzone attribute of length 3.. But if data are
POSIXct, then the tzone attribute must be of length 1 and no error will be
generated.

I'll also check other functions that might generate dates and extract time
zone info.

**Comment by jharcum** [comment]
Dave,

Ok, thank you. Please remember that it is regularSeries line 59 that is doing the POSIXlt conversion. (i.e., I'm passing a POSIXct variable and it is being converted to POSIXlt with line 59)

**Comment by dlorenz-usgs** [comment]
Ok, but I actually modified the extraction code on what is now line 53, so
that the variable tzone only has length 1. Otherwise both current lines 57
and 64 would need to be modified. (I stripped some of the old and no longer
necessary history comments, so the line numbers changed).

**Comment by jharcum** [comment]
cool/thanks.

**Comment by jharcum** [comment]
Confirmed that it works. Again thank you.
